<?php

include_once('conference_program.features.inc');

/**
 * Implementation of hook_init().
 */
function conference_program_init() {
  drupal_add_css(drupal_get_path('module', 'conference_program') .'/conference_program.css');
}
  
/**
 * Implementation of hook_date_format_types().
 */
function conference_program_date_format_types() {
  return array(
    'day' => t('Day'),
    'time' => t('Time'),
  );
}

/**
 * Implementation of hook_date_formats().
 */
function conference_program_date_formats() {
  $formats = array();
  $formats[] = array(
    'type' => 'day',
    'format' => 'l, j F Y',
    'locales' => array(),
  );
  $formats[] = array(
    'type' => 'time',
    'format' => 'H:i',
    'locales' => array(),
  );
  return $formats;
}
